package com.realestate.agentsystem.model;

import lombok.Data;
import java.time.LocalDateTime;

@Data
public class Appointment {
    private String id;
    private String userId;
    private String agentId;
    private LocalDateTime dateTime;
    private String status; // SCHEDULED, COMPLETED, CANCELLED
    private String propertyType;
    private String location;

    // Constructors, getters and setters will be generated by Lombok
}